---
- hosts: stage
  become: true

  vars_files:
    - private.yml

  vars:
    release: jammy
    www_cname: false

  roles:
    - common
    - postgres
    - redis
    - nginx
    - mastodon
    - monitoring
    - backup
