---
- name: Make sure needed directories exist
  file:
    path: "{{ root_bin }}"
    state: directory
    recurse: yes
    mode: "700"
    owner: root
    group: root

- name: Copy init script
  template:
    src: init.sh.j2
    dest: "{{ root_bin }}init.sh"
    owner: root
    group: root
    mode: "700"
