---
- name: Add node repository gpg key
  apt_key:
    url: "{{ node.key_url }}"
    id: "{{ node.key_id }}"
    state: present

- name: Add node repository
  become: yes
  apt_repository:
    repo: "{{ node.repo_string }}"
    state: present
    filename: node
    update_cache: yes

- name: Add yarn repository gpg key
  apt_key:
    url: "{{ yarn.key_url }}"
    id: "{{ yarn.key_id }}"
    state: present

- name: Add yarn repository
  become: yes
  apt_repository:
    repo: "{{ yarn.repo_string }}"
    state: present
    filename: yarn
    update_cache: yes

- name: Install mastodon dependencies
  apt:
    pkg:
    - imagemagick
    - ffmpeg
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - file
    - git-core
    - g++
    - libprotobuf-dev
    - protobuf-compiler
    - pkg-config
    - nodejs
    - gcc
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm-dev
    - yarn
    - libidn11-dev
    - libicu-dev
    - libjemalloc-dev
    state: present
