---
- name: Add node repository gpg key
  apt_key:
    data: "{{ lookup('file', 'node.asc') }}"
    id: 9FD3B784BC1C6FC31A8A0A1C1655A0AB68576280
    state: present

- name: Add node repository
  become: yes
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ node_version }}.x {{ release }} main"
    state: present
    filename: node
    update_cache: yes

- name: Add yarn repository gpg key
  apt_key:
    data: "{{ lookup('file', 'yarn.asc') }}"
    id: 72ECF46A56B4AD39C907BBB71646B01B86E50310
    state: present

- name: Add yarn repository
  become: yes
  apt_repository:
    repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
    state: present
    filename: yarn
    update_cache: yes

- name: Install mastodon dependencies
  apt:
    pkg:
    - imagemagick
    - ffmpeg
    - libpq-dev
    - libxml2-dev
    - libxslt1-dev
    - file
    - git-core
    - g++
    - libprotobuf-dev
    - protobuf-compiler
    - pkg-config
    - nodejs
    - gcc
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm-dev
    - yarn
    - libidn11-dev
    - libicu-dev
    - libjemalloc-dev
    state: present
